version: '3.8'
services:  
  mongodb-api:
    build: registry.cn-hangzhou.aliyuncs.com/dafan-ai/mongodb-api-python:1.4 
    container_name: python-mongodb-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=9
      - REDIS_PASSWORD=lobbyredisLock527788
    depends_on:
      - redis
    networks:
      - mongodb-api-network

  redis:
    image: redis:7-alpine
    container_name: mongodb-api-redis
    restart: always
    command: redis-server --requirepass lobbyredisLock527788
    ports:
      - "31337:6379"
    volumes:
      - redis-data:/data
    networks:
      - mongodb-api-network

networks:
  mongodb-api-network:
    driver: bridge

volumes:
  redis-data:
    driver: local